### ISSUE TITLE
Missing client packages: Inform on server log

### ISSUE THREAD

**Issue by derwaldgeist** [Meteor-Community-Packages/check-npm-versions#14]
If I understand this package correctly, it will output an error message in the browser console, if a client package is missing. This can easily be missed. It would be better if the server console would log that problem, too. Is there any chance to make this happen, if the package is only required on the client? I wouldn't want to require() it on the server, especially if it is a very client-centric package like a jquery plugin.

**Comment by copleykj** [comment]
Checks that run on the server will report in the server console even if the package requires the npm module to be used on the client.
