### ISSUE TITLE
How to accept minor version changes based on semver?

### ISSUE THREAD

**Issue by derwaldgeist** [Meteor-Community-Packages/check-npm-versions#15]
I could get this package only to work if the version stated in `package.json` is exactly the same as the version defined via `checkNpmVersions`. However, if I use semver to indicate that any minor update would be fine as well, `checkNpmVersion` complains that the versions do not mismatch. It seems as if it won't accept version statements like `^2.3.1`, although it doesn't complain if you use them.

**Comment by copleykj** [comment]
This should be easily accomplished by using an `x` at the appropriate position in the version string.

`2.x.x`  should accept all minor and patch versions following the v2 major release
`2.3.x` should accept all patch versions following the v2.3 minor release
