### ISSUE TITLE
Use with Package.registerBuildPlugin?

### ISSUE THREAD

**Issue by GeoffreyBooth** [Meteor-Community-Packages/check-npm-versions#17]
I’m trying to use this to update the [`coffeescript` package](https://github.com/meteor/meteor/tree/devel/packages/non-core/coffeescript) to use whatever version of the NPM `coffeescript` module the project has installed. I can’t seem to get it to work. This is in [`package.js`](https://github.com/meteor/meteor/blob/devel/packages/non-core/coffeescript/package.js):

```js
Package.registerBuildPlugin({
  name: 'compileCoffeescript',
  use: [
    'caching-compiler',
    'ecmascript',
    'tmeasday:check-npm-versions@0.3.1'
  ],
  sources: ['plugin/compile-coffeescript.js'],
  npmDependencies: {
    'source-map': '0.5.6'
  }
});
```

And this is the top of [`plugin/compile-coffeescript.js`](https://github.com/meteor/meteor/blob/devel/packages/non-core/coffeescript/plugin/compile-coffeescript.js):

```js
import { checkNpmVersions } from 'meteor/tmeasday:check-npm-versions';
checkNpmVersions({
  coffeescript: '2.0.0-beta3',
}, 'coffeescript');

import CoffeeScript from 'coffeescript';
import { BabelCompiler } from 'meteor/babel-compiler';
import { SourceMapConsumer, SourceMapGenerator } from 'source-map';
```

I keep getting `error: Can't load npm module 'coffeescript' from packages/modules-runtime.js. Check your Npm.depends().`

Any ideas? Does `check-npm-versions` not work in the context of `Package.registerBuildPlugin`?

**Comment by mitar** [comment]
I think this was the issue of plugins not being able to access modules in `node_modules` from the app. I think this works now, at least it seems in one other plugin (minifier) in Meteor 1.6.1.1.

**Comment by copleykj** [comment]
Just for future reference, I think this may have been due to import hoisting as mentioned in the readme file.

**Comment by copleykj** [comment]
Closing due to age.
