### ISSUE TITLE
Bringing this package under community maintenance.

### ISSUE THREAD

**Issue by copleykj** [Meteor-Community-Packages/check-npm-versions#21]
Hey Tom,
There is a community proposal (https://github.com/Meteor-Community-Packages/organization/issues/27) to bring this package under community maintenance. Rather than forking and republishing, would you be willing to transfer ownership of this package to the Meteor-Community-Packages org?

**Comment by tmeasday** [comment]
Sure thing, what do I need to do?

**Comment by copleykj** [comment]
Awesome! I've sent you an invite to join the org. Once accepted you should be able to transfer the repo to the org. After that, we'll just need `communitypackages` meteor org added as a maintainer by running `meteor admin maintainers tmeasday:check-npm-versions --add communitypackages`.

**Comment by tmeasday** [comment]
@copleykj done!

**Comment by copleykj** [comment]
Thanks so much!
