### ISSUE TITLE
1.0.0 breaks IE11 via semver 7.3.4

### ISSUE THREAD

**Issue by perbergland** [Meteor-Community-Packages/check-npm-versions#24]
Not sure when it stopped working but it crashes IE11 on load now.

![image](https://user-images.githubusercontent.com/2690254/117173489-1bb9e280-adcd-11eb-9edc-d4fd4aa7e588.png)

**Comment by perbergland** [comment]
I have now verified that downgrading to semver 6.3.0 resolves the problem.

Change in package.js:

Npm.depends({ semver: '6.3.0' });

**Comment by perbergland** [comment]
To work around this problem, I needed to copy the package source into my app packages directory. Would you consider downgrading the semver version and release an updated package (or somehow run babel on semver in web.browser.legacy to make it compatible with IE)?

**Comment by perbergland** [comment]
It would be nice if a package could also force "recompilation" of its npm dependencies for legacy but I don’t think that’s possible, is it?

https://github.com/meteor/meteor/pull/10603

**Comment by StorytellerCZ** [comment]
@perbergland Could you create a PR with a fix?

**Comment by perbergland** [comment]
will do!

**Comment by StorytellerCZ** [comment]
Thanks a lot!

**Comment by copleykj** [comment]
Maybe an issue should also be filed on the [semver](https://github.com/semver/semver) repo? I'd hate to see this locked into an outdated version of semver.

**Comment by perbergland** [comment]
It seems like a very deliberate move on their behalf - https://github.com/npm/node-semver/blob/master/CHANGELOG.md (7.0.0) and that the package is only meant to be used server-side with nodejs.

I see in the history of this package that there was an attempt to make it server-side only also for meteor but that you backed out of the change. What is missing in meteor to make that move?

**Comment by copleykj** [comment]
> It seems like a very deliberate move on their behalf - https://github.com/npm/node-semver/blob/master/CHANGELOG.md (7.0.0) and that the package is only meant to be used server-side with nodejs.

Well that's unfortunate.

> I see in the history of this package that there was an attempt to make it server-side only also for meteor but that you backed out of the change. What is missing in meteor to make that move?

Admittedly its been quite a while since I tried to move this to a server only package so the details are a bit hazy, but from what I recall is that Meteor's build system doesn't allow us to get the information we need about client packages from server code and so it wasn't possible. Honestly though, I feel like this package should have been a temporary fix and something better should have been baked into the build tool.
