### ISSUE TITLE
Update code to be compatible with typescript  (4.8+) strict mode

### ISSUE THREAD

**Issue by perbergland** [Meteor-Community-Packages/check-npm-versions#39]
I get the following error when using the package with zodern:types (it brings in the implementation file as a typings file)

```
.meteor/local/types/node_modules/package-types/tmeasday_check-npm-versions/package/web.browser.legacy/check-npm-versions.ts (28,21): 'e' is of type 'unknown'.
```

The problem is that in strict mode, catch (e) is now by default catch (e:unknown)  - I believe this was introduced in typescript 4.8.

Please change the code to use `catch (e: any)`:

```
if (semver.satisfies(installedVersion, range)) {
      return true;
    } else {
      return installedVersion;
    }
  } catch (e: any) {
    // XXX add something to the tool to make this more reliable
    const message = e.toString();
    // One message comes out of the install npm package the other from npm directly
    if (message.includes('Cannot find module') === true || message.includes("Can't find npm module") === true) {
      return false;
    } else {
      throw e;
    }
  }
```

**Comment by perbergland** [comment]
The workaround for now is to set `"useUnknownInCatchVariables": false` in your tsconfig.json file

**Comment by perbergland** [comment]
Another fix would be to generate and include a .d.ts typings file in the package

**Comment by StorytellerCZ** [comment]
I think doing types with `zodern:types` is a good step.

**Comment by StorytellerCZ** [comment]
Looking at the code the fix is already included. Closing this for clarity.
