### ISSUE TITLE
Typescript version needs to be upgraded to work with Meteor 3.0

### ISSUE THREAD

**Issue by kolyasya** [Meteor-Community-Packages/check-npm-versions#44]
Hey, I heavily rely on **check-npm-versions** package in my projects, but can't update them to Meteor 3.0 RC because of constraints

<img width="519" alt="image" src="https://github.com/Meteor-Community-Packages/check-npm-versions/assets/3371143/04643296-d95f-4e21-a637-9a91eea96b7e">

**Comment by kolyasya** [comment]
Ping

**Comment by StorytellerCZ** [comment]
v2.0.0 has version constrains linked to Meteor v3.0.1 which resolved this issue. The next release will add version resolution for Meteor v3.1.
